# SPDX-FileCopyrightText: The Threadbare Authors
# SPDX-License-Identifier: MPL-2.0
name: "Build and Export Game"
on:
  workflow_dispatch:
  pull_request:
  release:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  GODOT_VERSION: 4.4.1
  PCK_NAME: threadbare

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Godot Engine downloads
        id: cache-godot
        uses: actions/cache@v4
        with:
          path: |
            build/godot
            build/._sc_
            build/editor_data/export_templates/${{ env.GODOT_VERSION }}.stable
          key: godot-${{ env.GODOT_VERSION }}

      - name: Download Godot Engine from GitHub release
        id: download
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          mkdir -p build && cd build

          # Download Godot Engine itself
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip && \
          unzip Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip && \
          mv Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot

          # Download export templates
          mkdir -p editor_data/export_templates
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz && \
          unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz && \
          mv templates editor_data/export_templates/${GODOT_VERSION}.stable

          # Tell Godot Engine to run in "self-contained" mode so it looks for
          # templates here instead of in ~/.local/share/godot/
          touch ._sc_

      - name: Build / Web
        run: |
          mkdir -v -p build/web && cd build

          # Note that the export path can be confusing; it's relative to the
          # Godot project path, NOT necessarily the current directory or Godot
          # binary location
          ./godot --headless --verbose --path ../ --export-release "Web" ./build/web/index.html

      - name: Build / PCK
        run: |
          mkdir -v -p build && cd build

          # Note that the export path can be confusing; it's relative to the
          # Godot project path, NOT necessarily the current directory or Godot
          # binary location
          ./godot --headless --verbose --path ../ --export-pack "Linux" ./build/${PCK_NAME}.pck

      - name: Upload Artifact / Web
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web

      - name: Upload Artifact / PCK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PCK_NAME }}
          path: build/${{ env.PCK_NAME }}.pck

  flatpak:
    name: Build / Flatpak
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.PCK_NAME }}
        path: build
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: threadbare.flatpak
        manifest-path: org.endlessos.threadbare.yml
        cache-key: "flatpak-builder-${{ github.sha }}"

  release:
    name: Upload Release / PCK
    needs: build
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PCK_NAME }}

      - name: Upload to Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mv '${{ env.PCK_NAME }}.pck' '${{ env.PCK_NAME }}-${{ github.ref_name }}.pck'
          gh release upload '${{ github.ref_name }}' '${{ env.PCK_NAME }}-${{ github.ref_name }}.pck' --repo '${{ github.repository }}'
