# SPDX-FileCopyrightText: The Threadbare Authors
# SPDX-License-Identifier: MPL-2.0
name: "Build Flatpak"
on:
  workflow_run:
    workflows: ["Build and Export Game"]
    types: [completed]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  flatpak:
    name: Build Flatpak
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.ref == 'refs/heads/main' || github.event_name == 'release') }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
        name: pck
        path: build
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: threadbare.flatpak
        manifest-path: org.endlessos.threadbare.yml
        cache-key: "flatpak-builder-${{ github.sha }}"
